import "dotenv/config";
import { PrismaClient } from "@/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database...");

  // ── Clean existing data ──────────────────────────────────────────────
  await prisma.review.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.car.deleteMany();
  await prisma.company.deleteMany();
  await prisma.city.deleteMany();
  await prisma.user.deleteMany();
  await prisma.page.deleteMany();

  // ── Cities ───────────────────────────────────────────────────────────
  const cities = await Promise.all([
    prisma.city.create({
      data: {
        slug: "tashkent",
        nameRu: "Ташкент",
        nameUz: "Toshkent",
        nameEn: "Tashkent",
      },
    }),
    prisma.city.create({
      data: {
        slug: "samarkand",
        nameRu: "Самарканд",
        nameUz: "Samarqand",
        nameEn: "Samarkand",
      },
    }),
    prisma.city.create({
      data: {
        slug: "bukhara",
        nameRu: "Бухара",
        nameUz: "Buxoro",
        nameEn: "Bukhara",
      },
    }),
    prisma.city.create({
      data: {
        slug: "fergana",
        nameRu: "Фергана",
        nameUz: "Farg'ona",
        nameEn: "Fergana",
      },
    }),
    prisma.city.create({
      data: {
        slug: "namangan",
        nameRu: "Наманган",
        nameUz: "Namangan",
        nameEn: "Namangan",
      },
    }),
    prisma.city.create({
      data: {
        slug: "nukus",
        nameRu: "Нукус",
        nameUz: "Nukus",
        nameEn: "Nukus",
      },
    }),
  ]);

  const [tashkent, samarkand, bukhara, fergana, namangan, nukus] = cities;

  // ── Admin user ───────────────────────────────────────────────────────
  const admin = await prisma.user.create({
    data: {
      email: "admin@rentcar.uz",
      phone: "+998901234567",
      name: "RentCar Admin",
      role: "ADMIN",
      language: "RU",
      passwordHash: "$2b$10$placeholder_hash_replace_me",
      isVerified: true,
    },
  });

  // ── Owner users ──────────────────────────────────────────────────────
  const owner1 = await prisma.user.create({
    data: {
      email: "owner1@rentcar.uz",
      phone: "+998901111111",
      name: "Азиз Каримов",
      role: "OWNER",
      language: "RU",
      passwordHash: "$2b$10$placeholder_hash_replace_me",
      isVerified: true,
    },
  });

  const owner2 = await prisma.user.create({
    data: {
      email: "owner2@rentcar.uz",
      phone: "+998902222222",
      name: "Дилшод Рахимов",
      role: "OWNER",
      language: "UZ",
      passwordHash: "$2b$10$placeholder_hash_replace_me",
      isVerified: true,
    },
  });

  // ── Companies ────────────────────────────────────────────────────────
  const company1 = await prisma.company.create({
    data: {
      slug: "tashkent-avto",
      name: "Tashkent Avto",
      description: "Крупнейший автопарк в Ташкенте. Более 50 автомобилей.",
      phone: "+998901111111",
      email: "info@tashkentavto.uz",
      address: "ул. Амира Темура, 100",
      ownerId: owner1.id,
      isVerified: true,
    },
  });

  const company2 = await prisma.company.create({
    data: {
      slug: "silk-road-cars",
      name: "Silk Road Cars",
      description: "Аренда авто по всему Узбекистану. Доставка в аэропорт.",
      phone: "+998902222222",
      email: "info@silkroadcars.uz",
      address: "ул. Навои, 55",
      ownerId: owner2.id,
      isVerified: true,
    },
  });

  // ── Cars (25 demo) ───────────────────────────────────────────────────
  const carsData = [
    // ECONOMY — Tashkent
    {
      slug: "chevrolet-spark-2023-tashkent",
      brand: "Chevrolet",
      model: "Spark",
      year: 2023,
      category: "ECONOMY" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 120_000,
      deposit: 500_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Магнитола", "USB"],
      description: "Экономичный городской автомобиль. Идеален для поездок по Ташкенту.",
      isOwnFleet: true,
    },
    {
      slug: "chevrolet-cobalt-2023-tashkent",
      brand: "Chevrolet",
      model: "Cobalt",
      year: 2023,
      category: "ECONOMY" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 150_000,
      deposit: 600_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Магнитола", "USB", "Центральный замок"],
      description: "Просторный седан для города. Вместительный багажник.",
      isOwnFleet: true,
    },
    {
      slug: "chevrolet-cobalt-2022-samarkand",
      brand: "Chevrolet",
      model: "Cobalt",
      year: 2022,
      category: "ECONOMY" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 140_000,
      deposit: 500_000,
      mileageLimit: 250,
      cityId: samarkand.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Магнитола"],
      description: "Надёжный вариант для путешествия по Самарканду.",
      isOwnFleet: true,
    },
    {
      slug: "daewoo-gentra-2021-fergana",
      brand: "Chevrolet",
      model: "Gentra",
      year: 2021,
      category: "ECONOMY" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 130_000,
      deposit: 400_000,
      mileageLimit: 250,
      cityId: fergana.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Электростеклоподъёмники"],
      description: "Отличный бюджетный вариант для Ферганской долины.",
      isOwnFleet: true,
    },
    // ECONOMY — more
    {
      slug: "chevrolet-spark-2022-bukhara",
      brand: "Chevrolet",
      model: "Spark",
      year: 2022,
      category: "ECONOMY" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 110_000,
      deposit: 400_000,
      mileageLimit: 250,
      cityId: bukhara.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Магнитола"],
      description: "Компактный и экономичный. Для поездок по историческому центру.",
      isOwnFleet: true,
    },
    // COMFORT
    {
      slug: "chevrolet-lacetti-2023-tashkent",
      brand: "Chevrolet",
      model: "Lacetti",
      year: 2023,
      category: "COMFORT" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 200_000,
      deposit: 800_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Круиз-контроль", "Камера заднего вида", "USB"],
      description: "Комфортный седан с автоматической коробкой. Подойдёт для семьи.",
      isOwnFleet: true,
    },
    {
      slug: "hyundai-accent-2023-tashkent",
      brand: "Hyundai",
      model: "Accent",
      year: 2023,
      category: "COMFORT" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 220_000,
      deposit: 800_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Apple CarPlay", "Камера заднего вида", "Подогрев сидений"],
      description: "Современный и надёжный. Идеален для города и трассы.",
      isOwnFleet: true,
    },
    {
      slug: "kia-cerato-2022-tashkent",
      brand: "Kia",
      model: "Cerato",
      year: 2022,
      category: "COMFORT" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 250_000,
      deposit: 1_000_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Круиз-контроль", "Камера заднего вида", "Навигация"],
      description: "Стильный седан с отличной комплектацией.",
      isOwnFleet: true,
    },
    // SUV
    {
      slug: "chevrolet-tracker-2024-tashkent",
      brand: "Chevrolet",
      model: "Tracker",
      year: 2024,
      category: "SUV" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 300_000,
      deposit: 1_500_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Apple CarPlay", "Камера 360", "Подогрев сидений", "Круиз-контроль"],
      description: "Компактный кроссовер. Отлично подходит для города и загородных поездок.",
      isOwnFleet: true,
    },
    {
      slug: "kia-sportage-2023-tashkent",
      brand: "Kia",
      model: "Sportage",
      year: 2023,
      category: "SUV" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 350_000,
      deposit: 2_000_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Панорамная крыша", "Камера 360", "Подогрев руля", "Вентиляция сидений"],
      description: "Популярный кроссовер с просторным салоном и полным приводом.",
      isOwnFleet: true,
    },
    {
      slug: "chevrolet-equinox-2023-samarkand",
      brand: "Chevrolet",
      model: "Equinox",
      year: 2023,
      category: "SUV" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 320_000,
      deposit: 1_500_000,
      mileageLimit: 300,
      cityId: samarkand.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Apple CarPlay", "Камера заднего вида", "Круиз-контроль"],
      description: "Просторный кроссовер для путешествий по Шёлковому пути.",
      isOwnFleet: true,
    },
    {
      slug: "hyundai-tucson-2023-tashkent",
      brand: "Hyundai",
      model: "Tucson",
      year: 2023,
      category: "SUV" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 380_000,
      deposit: 2_000_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кондиционер", "Панорамная крыша", "Камера 360", "Навигация", "Подогрев сидений"],
      description: "Современный SUV с передовыми технологиями.",
      isOwnFleet: true,
    },
    // BUSINESS
    {
      slug: "toyota-camry-2024-tashkent",
      brand: "Toyota",
      model: "Camry",
      year: 2024,
      category: "BUSINESS" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 500_000,
      deposit: 3_000_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "Климат-контроль", "JBL аудиосистема", "Камера 360", "Подогрев/вентиляция сидений"],
      description: "Бизнес-седан Toyota Camry. Идеален для деловых поездок и встреч.",
      isOwnFleet: true,
    },
    {
      slug: "kia-k5-2023-tashkent",
      brand: "Kia",
      model: "K5",
      year: 2023,
      category: "BUSINESS" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 400_000,
      deposit: 2_500_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "Климат-контроль", "Bose аудиосистема", "Камера 360", "Навигация"],
      description: "Стильный бизнес-седан с премиальным оснащением.",
      isOwnFleet: true,
    },
    {
      slug: "toyota-camry-2023-samarkand",
      brand: "Toyota",
      model: "Camry",
      year: 2023,
      category: "BUSINESS" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "HYBRID" as const,
      seats: 5,
      pricePerDay: 480_000,
      deposit: 3_000_000,
      mileageLimit: 400,
      cityId: samarkand.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кожаный салон", "Климат-контроль", "Камера 360", "Подогрев сидений"],
      description: "Гибридная Camry — экономичная и мощная. Для поездок Самарканд-Ташкент.",
      isOwnFleet: true,
    },
    // BUSINESS — Electric
    {
      slug: "byd-seal-2024-tashkent",
      brand: "BYD",
      model: "Seal",
      year: 2024,
      category: "BUSINESS" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "ELECTRIC" as const,
      seats: 5,
      pricePerDay: 450_000,
      deposit: 3_000_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "Панорамная крыша", "Harman Kardon", "Автопилот", "Быстрая зарядка"],
      description: "Полностью электрический седан BYD Seal. Запас хода 570 км.",
      isOwnFleet: true,
    },
    {
      slug: "byd-han-2024-tashkent",
      brand: "BYD",
      model: "Han",
      year: 2024,
      category: "BUSINESS" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "ELECTRIC" as const,
      seats: 5,
      pricePerDay: 480_000,
      deposit: 3_500_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "Вращающийся экран", "NFC ключ", "Автопилот", "Двухзонный климат"],
      description: "Премиальный электрический седан. Бесшумный и мощный.",
      isOwnFleet: true,
    },
    // MINIVAN
    {
      slug: "kia-carnival-2023-tashkent",
      brand: "Kia",
      model: "Carnival",
      year: 2023,
      category: "MINIVAN" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "DIESEL" as const,
      seats: 8,
      pricePerDay: 550_000,
      deposit: 3_000_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "Три ряда сидений", "Электродвери", "Климат-контроль 3 зоны", "Камера 360"],
      description: "Просторный минивэн для большой семьи или группы туристов.",
      isOwnFleet: true,
    },
    {
      slug: "hyundai-staria-2023-tashkent",
      brand: "Hyundai",
      model: "Staria",
      year: 2023,
      category: "MINIVAN" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "DIESEL" as const,
      seats: 9,
      pricePerDay: 600_000,
      deposit: 3_500_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон", "9 мест", "Электродвери", "Климат-контроль", "USB на каждом ряду"],
      description: "Футуристичный минивэн для больших групп. Идеален для трансфера.",
      isOwnFleet: true,
    },
    // PREMIUM
    {
      slug: "toyota-prado-2024-tashkent",
      brand: "Toyota",
      model: "Land Cruiser Prado",
      year: 2024,
      category: "PREMIUM" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "DIESEL" as const,
      seats: 7,
      pricePerDay: 900_000,
      deposit: 5_000_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Полный привод", "Кожаный салон", "JBL", "Камера 360", "Пневмоподвеска"],
      description: "Легендарный внедорожник. Для VIP-трансфера и экспедиций по Узбекистану.",
      isOwnFleet: true,
    },
    {
      slug: "toyota-land-cruiser-300-2023-tashkent",
      brand: "Toyota",
      model: "Land Cruiser 300",
      year: 2023,
      category: "PREMIUM" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "DIESEL" as const,
      seats: 7,
      pricePerDay: 1_200_000,
      deposit: 8_000_000,
      mileageLimit: 400,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Полный привод", "Кожаный салон", "JBL Premium", "Подогрев/вентиляция всех рядов", "Камера 360"],
      description: "Флагман Toyota. Максимальный комфорт для длительных путешествий.",
      isOwnFleet: true,
    },
    {
      slug: "mercedes-s-class-2023-tashkent",
      brand: "Mercedes-Benz",
      model: "S-Class",
      year: 2023,
      category: "PREMIUM" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 1_500_000,
      deposit: 10_000_000,
      mileageLimit: 300,
      cityId: tashkent.id,
      ownerId: owner1.id,
      companyId: company1.id,
      features: ["Кожаный салон Nappa", "Burmester 4D", "Массаж сидений", "Ambient Lighting", "Автопилот"],
      description: "Представительский класс. Для особых случаев и VIP-мероприятий.",
      isOwnFleet: true,
    },
    // COMFORT — other cities
    {
      slug: "chevrolet-lacetti-2022-bukhara",
      brand: "Chevrolet",
      model: "Lacetti",
      year: 2022,
      category: "COMFORT" as const,
      transmission: "MANUAL" as const,
      fuelType: "GAS" as const,
      seats: 5,
      pricePerDay: 180_000,
      deposit: 700_000,
      mileageLimit: 300,
      cityId: bukhara.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Магнитола", "USB", "Центральный замок"],
      description: "Комфортный вариант для экскурсий по Бухаре.",
      isOwnFleet: true,
    },
    {
      slug: "hyundai-accent-2022-namangan",
      brand: "Hyundai",
      model: "Accent",
      year: 2022,
      category: "COMFORT" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 200_000,
      deposit: 800_000,
      mileageLimit: 300,
      cityId: namangan.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Apple CarPlay", "Камера заднего вида"],
      description: "Современный седан для поездок по Наманганской области.",
      isOwnFleet: true,
    },
    {
      slug: "chevrolet-tracker-2023-bukhara",
      brand: "Chevrolet",
      model: "Tracker",
      year: 2023,
      category: "SUV" as const,
      transmission: "AUTOMATIC" as const,
      fuelType: "PETROL" as const,
      seats: 5,
      pricePerDay: 280_000,
      deposit: 1_500_000,
      mileageLimit: 300,
      cityId: bukhara.id,
      ownerId: owner2.id,
      companyId: company2.id,
      features: ["Кондиционер", "Apple CarPlay", "Камера заднего вида", "Круиз-контроль"],
      description: "Кроссовер для поездок Бухара—Самарканд и обратно.",
      isOwnFleet: true,
    },
  ];

  for (const carData of carsData) {
    await prisma.car.create({
      data: {
        ...carData,
        images: [],
        isAvailable: true,
        isApproved: true,
      },
    });
  }

  console.log(`Seeded:`);
  console.log(`  ${cities.length} cities`);
  console.log(`  3 users (1 admin, 2 owners)`);
  console.log(`  2 companies`);
  console.log(`  ${carsData.length} cars`);
  console.log("Done!");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
